spring:
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
---

spring:
  profiles: test
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
---

spring:
  profiles: prod
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
---

spring:
  profiles: local
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456