spring:
  profiles:
   active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root

quartz:
  profiles:
   active: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.20.16.74:3306/market?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: market
    password: market

---

spring:
  profiles:
   active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root

quartz:
  profiles:
   active: test
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.20.16.74:3306/market?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: market
    password: market